In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[2540, 8648, 5787, 5238],
 [2540, 8648, 5787, 2520],
 [2540, 4199, 5787, 4688],
 [3856, 8754, 3148, 3283, 7993],
 [3856, 8754, 3148, 3283, 3479],
 [4049, 2540, 4582, 5787, 6588],
 [7433, 4181, 7955, 3283]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2540 8648 5787 5238]
 [   0    0    0    0 2540 8648 5787 2520]
 [   0    0    0    0 2540 4199 5787 4688]
 [   0    0    0 3856 8754 3148 3283 7993]
 [   0    0    0 3856 8754 3148 3283 3479]
 [   0    0    0 4049 2540 4582 5787 6588]
 [   0    0    0    0 7433 4181 7955 3283]]


In [11]:
## feature representation
dim=10

In [12]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [14]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [15]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 102ms/step


array([[[-3.49937901e-02,  1.18056908e-02, -4.74375598e-02,
         -1.52590163e-02,  8.25390965e-03,  3.63730453e-02,
          6.32070377e-03, -4.37310226e-02, -2.44192369e-02,
          1.72110535e-02],
        [-3.49937901e-02,  1.18056908e-02, -4.74375598e-02,
         -1.52590163e-02,  8.25390965e-03,  3.63730453e-02,
          6.32070377e-03, -4.37310226e-02, -2.44192369e-02,
          1.72110535e-02],
        [-3.49937901e-02,  1.18056908e-02, -4.74375598e-02,
         -1.52590163e-02,  8.25390965e-03,  3.63730453e-02,
          6.32070377e-03, -4.37310226e-02, -2.44192369e-02,
          1.72110535e-02],
        [-3.49937901e-02,  1.18056908e-02, -4.74375598e-02,
         -1.52590163e-02,  8.25390965e-03,  3.63730453e-02,
          6.32070377e-03, -4.37310226e-02, -2.44192369e-02,
          1.72110535e-02],
        [ 2.27282383e-02,  2.76121534e-02, -3.25318575e-02,
         -1.72760971e-02, -4.15333882e-02, -4.27447446e-02,
          1.33537762e-02,  4.05520685e-02, -2.337265

In [16]:
embedded_docs[0]

array([   0,    0,    0,    0, 2540, 8648, 5787, 5238])

In [17]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 33ms/step


array([[-3.4993790e-02,  1.1805691e-02, -4.7437560e-02, -1.5259016e-02,
         8.2539096e-03,  3.6373045e-02,  6.3207038e-03, -4.3731023e-02,
        -2.4419237e-02,  1.7211054e-02],
       [-3.4993790e-02,  1.1805691e-02, -4.7437560e-02, -1.5259016e-02,
         8.2539096e-03,  3.6373045e-02,  6.3207038e-03, -4.3731023e-02,
        -2.4419237e-02,  1.7211054e-02],
       [-3.4993790e-02,  1.1805691e-02, -4.7437560e-02, -1.5259016e-02,
         8.2539096e-03,  3.6373045e-02,  6.3207038e-03, -4.3731023e-02,
        -2.4419237e-02,  1.7211054e-02],
       [-3.4993790e-02,  1.1805691e-02, -4.7437560e-02, -1.5259016e-02,
         8.2539096e-03,  3.6373045e-02,  6.3207038e-03, -4.3731023e-02,
        -2.4419237e-02,  1.7211054e-02],
       [ 2.2728238e-02,  2.7612153e-02, -3.2531857e-02, -1.7276097e-02,
        -4.1533388e-02, -4.2744745e-02,  1.3353776e-02,  4.0552069e-02,
        -2.3372658e-03,  4.7009934e-02],
       [-3.0580759e-02,  3.8314011e-02,  4.1061725e-02, -1.7719947e-02,
   